name: warehouse_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+5
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_zxing: ^1.5.1
  image_picker: ^1.0.5
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: louis
  #     fonts:
  #       - asset: assets/fonts/Louis.ttf
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
